name: flutter_application_1
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.16
  firebase_auth: ^3.3.19
  get: ^4.6.5
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.17
  firebase_messaging: ^11.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true


  assets:
    - img/Loading_icon.gif
  #   - images/a_dot_ham.jpeg




  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf

